# Generated by Django 3.0.7 on 2020-07-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('zip_code', models.CharField(max_length=111)),
            ],
        ),
    ]
