# Generated by Django 3.0.7 on 2020-07-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
